# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='源文件')),
                ('import_type', models.CharField(choices=[('EQUIPMENT', '设备与部件')], default='EQUIPMENT', max_length=20, verbose_name='导入类型')),
                ('status', models.CharField(choices=[('UPLOADED', '已上传'), ('VALIDATING', '校验中'), ('READY', '待执行'), ('RUNNING', '导入中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], db_index=True, default='UPLOADED', max_length=20, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('success_rows', models.PositiveIntegerField(default=0, verbose_name='成功行数')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='失败行数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='facilities.warehouse', verbose_name='目标仓库')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(verbose_name='行号')),
                ('field_name', models.CharField(blank=True, max_length=80, verbose_name='字段')),
                ('error_code', models.CharField(max_length=80, verbose_name='错误代码')),
                ('error_message', models.TextField(verbose_name='错误说明')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='data_imports.importbatch', verbose_name='导入批次')),
            ],
            options={
                'verbose_name': '导入错误',
                'verbose_name_plural': '导入错误',
                'ordering': ['batch', 'row_number'],
                'indexes': [models.Index(fields=['batch', 'row_number'], name='data_import_batch_i_c2be62_idx')],
            },
        ),
    ]
