# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('facilities', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='工单编号')),
                ('plan_due_at', models.DateTimeField(blank=True, null=True, verbose_name='计划期次')),
                ('work_type', models.CharField(choices=[('PREVENTIVE', '预防性维保'), ('CORRECTIVE', '故障维修'), ('INSPECTION', '巡检')], default='PREVENTIVE', max_length=16, verbose_name='工单类型')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '紧急')], db_index=True, default='MEDIUM', max_length=16, verbose_name='优先级')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('OPEN', '待分派'), ('ASSIGNED', '已分派'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '待验收'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], db_index=True, default='OPEN', max_length=16, verbose_name='状态')),
                ('title', models.CharField(max_length=180, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='到期时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.equipmentcomponent', verbose_name='部件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.equipment', verbose_name='设备')),
                ('source_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.maintenanceplan', verbose_name='来源计划')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='facilities.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '维保工单',
                'verbose_name_plural': '维保工单',
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80, verbose_name='动作')),
                ('from_status', models.CharField(blank=True, max_length=16, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=16, verbose_name='新状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workorders.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单日志',
                'verbose_name_plural': '工单日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(verbose_name='顺序')),
                ('title', models.CharField(max_length=160, verbose_name='任务标题')),
                ('instructions', models.TextField(blank=True, verbose_name='操作说明')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='必须上传照片')),
                ('status', models.CharField(choices=[('PENDING', '未开始'), ('DONE', '已完成'), ('NOT_APPLICABLE', '不适用')], default='PENDING', max_length=24, verbose_name='状态')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_work_order_tasks', to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单任务',
                'verbose_name_plural': '工单任务',
                'ordering': ['work_order', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['warehouse', 'status', 'due_at'], name='workorders__warehou_70edac_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('source_plan__isnull', False)), fields=('source_plan', 'plan_due_at'), name='uniq_work_order_plan_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='workordertask',
            constraint=models.UniqueConstraint(fields=('work_order', 'sequence'), name='uniq_work_order_task_sequence'),
        ),
    ]
