# Generated by Django 5.2.17 on 2026-08-24 23:06

import django.db.models.deletion
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.db import migrations, models


def next_due(current_due, unit, value):
    if unit == 'DAY':
        return current_due + timedelta(days=value)
    if unit == 'WEEK':
        return current_due + timedelta(weeks=value)
    if unit == 'MONTH':
        return current_due + relativedelta(months=value)
    if unit == 'QUARTER':
        return current_due + relativedelta(months=value * 3)
    if unit == 'YEAR':
        return current_due + relativedelta(years=value)
    return current_due + timedelta(days=value)


def migrate_active_plans(apps, schema_editor):
    MaintenancePlan = apps.get_model('maintenance', 'MaintenancePlan')
    WorkOrder = apps.get_model('workorders', 'WorkOrder')
    WorkOrderTask = apps.get_model('workorders', 'WorkOrderTask')
    for plan in MaintenancePlan.objects.filter(status='ACTIVE').select_related('template'):
        number = f"WO-MIG-{str(plan.id).replace('-', '')[:12].upper()}"
        order, created = WorkOrder.objects.get_or_create(
            number=number,
            defaults={
                'warehouse_id': plan.warehouse_id,
                'equipment_id': plan.equipment_id,
                'component_id': plan.component_id,
                'work_type': 'PREVENTIVE',
                'priority': plan.priority,
                'status': 'ASSIGNED' if plan.default_assignee_id else 'OPEN',
                'title': plan.name,
                'description': plan.template.description,
                'due_at': plan.next_due_at,
                'assignee_id': plan.default_assignee_id,
                'schedule_type': 'RECURRING',
                'recurrence_unit': plan.cycle_unit,
                'recurrence_interval': plan.cycle_value,
                'next_occurrence_at': next_due(plan.next_due_at, plan.cycle_unit, plan.cycle_value),
                'recurrence_active': True,
            },
        )
        if created:
            WorkOrderTask.objects.bulk_create([
                WorkOrderTask(
                    work_order_id=order.id,
                    sequence=task.sequence,
                    title=task.title,
                    instructions=task.instructions,
                    requires_photo=task.requires_photo,
                )
                for task in plan.template.tasks.all()
            ])


def remove_migrated_orders(apps, schema_editor):
    WorkOrder = apps.get_model('workorders', 'WorkOrder')
    WorkOrder.objects.filter(number__startswith='WO-MIG-').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('facilities', '0002_warehouserole_alter_warehousemembership_role'),
        ('maintenance', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='next_occurrence_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次生成时间'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='recurrence_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='周期有效'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='recurrence_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='周期结束时间'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1, verbose_name='周期数值'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='recurrence_source',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_occurrences', to='workorders.workorder', verbose_name='周期来源工单'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='recurrence_unit',
            field=models.CharField(blank=True, choices=[('DAY', '天'), ('WEEK', '周'), ('MONTH', '月'), ('QUARTER', '季度'), ('YEAR', '年')], max_length=16, verbose_name='周期单位'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='schedule_type',
            field=models.CharField(choices=[('ONE_TIME', '一次性工单'), ('RECURRING', '周期性工单')], db_index=True, default='ONE_TIME', max_length=16, verbose_name='工单频率'),
        ),
        migrations.RunPython(migrate_active_plans, remove_migrated_orders),
        migrations.AlterField(
            model_name='workorder',
            name='plan_due_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='旧版计划期次'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='source_plan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.maintenanceplan', verbose_name='旧版来源计划'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence_source__isnull', False)), fields=('recurrence_source', 'due_at'), name='uniq_recurring_work_order_occurrence'),
        ),
    ]
