# Generated by Django 5.2.17 on 2026-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_next_occurrence_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='due_at',
            field=models.DateTimeField(db_index=True, help_text='一次性工单使用该日期；周期性工单从该日期开始计算后续生成时间。', verbose_name='工单开始生成日期'),
        ),
    ]
