# Generated by Django 5.2.17 on 2026-09-03 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_workorder_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='photo',
            field=models.FileField(blank=True, upload_to='work-order-task-photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='现场照片'),
        ),
    ]
