# Generated by Django 5.2.17 on 2026-09-08 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workordertask_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='task_duration_hours',
            field=models.PositiveIntegerField(default=24, help_text='从工单开始生成起允许的处理时长，单位为小时。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='任务时间'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='due_at',
            field=models.DateTimeField(db_index=True, help_text='工单从该时间开始出现在相关人员的工作台；周期性工单从该时间计算后续生成时间。', verbose_name='工单开始生成日期'),
        ),
    ]
