# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=120, verbose_name='仓库名称')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('timezone', models.CharField(default='America/Chicago', max_length=64, verbose_name='时区')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], db_index=True, default='ACTIVE', max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', '仓库管理员'), ('ENGINEER', '自动化工程师'), ('SUPERVISOR', '维保主管'), ('VIEWER', '只读/审计')], default='ENGINEER', max_length=16, verbose_name='角色')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要仓库')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='接收通知')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='facilities.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库成员',
                'verbose_name_plural': '仓库成员',
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'user'), name='uniq_warehouse_user_membership'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='uniq_primary_warehouse_per_user')],
            },
        ),
    ]
