# Generated by Django 5.2.17 on 2026-08-24 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_ROLES = {
    'ADMIN': ('仓库管理员', True, True),
    'ENGINEER': ('自动化工程师', True, False),
    'SUPERVISOR': ('维保主管', True, True),
    'VIEWER': ('只读/审计', False, False),
}


def migrate_roles_forward(apps, schema_editor):
    WarehouseRole = apps.get_model('facilities', 'WarehouseRole')
    WarehouseMembership = apps.get_model('facilities', 'WarehouseMembership')
    roles = {}
    for code, (name, can_receive, can_manage) in DEFAULT_ROLES.items():
        roles[code] = WarehouseRole.objects.create(
            code=code,
            name=name,
            can_receive_work_orders=can_receive,
            can_manage_work_orders=can_manage,
        )
    for membership in WarehouseMembership.objects.all():
        role = roles.get(membership.legacy_role)
        if role is None:
            role, _ = WarehouseRole.objects.get_or_create(
                code=membership.legacy_role,
                defaults={'name': membership.legacy_role},
            )
        membership.role = role
        membership.save(update_fields=['role'])


def migrate_roles_backward(apps, schema_editor):
    WarehouseMembership = apps.get_model('facilities', 'WarehouseMembership')
    for membership in WarehouseMembership.objects.select_related('role'):
        membership.legacy_role = membership.role.code
        membership.save(update_fields=['legacy_role'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousemembership',
            old_name='role',
            new_name='legacy_role',
        ),
        migrations.CreateModel(
            name='WarehouseRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='角色编码')),
                ('name', models.CharField(max_length=80, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色说明')),
                ('can_receive_work_orders', models.BooleanField(default=False, verbose_name='可接收工单')),
                ('can_manage_work_orders', models.BooleanField(default=False, verbose_name='可管理工单')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('permissions', models.ManyToManyField(blank=True, help_text='角色成员可获得的 Django 系统权限。', to='auth.permission', verbose_name='系统权限')),
            ],
            options={
                'verbose_name': '仓库角色',
                'verbose_name_plural': '仓库角色',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='warehousemembership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='facilities.warehouserole', verbose_name='角色'),
        ),
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
        migrations.AlterField(
            model_name='warehousemembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='facilities.warehouserole', verbose_name='角色'),
        ),
        migrations.RemoveField(
            model_name='warehousemembership',
            name='legacy_role',
        ),
    ]
