# Generated by Django 5.2.17 on 2026-09-03 21:27

from django.db import migrations, models


ALLOWED_TIMEZONES = {
    "America/Los_Angeles",
    "America/Chicago",
    "America/New_York",
}


def normalize_user_timezones(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.exclude(timezone__in=ALLOWED_TIMEZONES).update(
        timezone="America/Chicago"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enable_staff_for_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('America/Los_Angeles', '美西时间'), ('America/Chicago', '美中时间'), ('America/New_York', '美东时间')], default='America/Chicago', max_length=64, verbose_name='时区'),
        ),
        migrations.RunPython(normalize_user_timezones, migrations.RunPython.noop),
    ]
