# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=80, verbose_name='对象类型')),
                ('entity_id', models.UUIDField(db_index=True, verbose_name='对象 ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME 类型')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='字节数')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='common_atta_entity__d59aea_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80, verbose_name='动作')),
                ('entity_type', models.CharField(db_index=True, max_length=80, verbose_name='对象类型')),
                ('entity_id', models.UUIDField(db_index=True, verbose_name='对象 ID')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='变更前')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='变更后')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='请求 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='facilities.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'created_at'], name='common_audi_warehou_f503e4_idx'), models.Index(fields=['entity_type', 'entity_id'], name='common_audi_entity__147a18_idx')],
            },
        ),
    ]
