# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, verbose_name='模板编码')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('name', models.CharField(max_length=140, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_templates', to='assets.assetcategory', verbose_name='适用分类')),
            ],
            options={
                'verbose_name': '维保模板',
                'verbose_name_plural': '维保模板',
                'ordering': ['code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='计划名称')),
                ('cycle_unit', models.CharField(choices=[('DAY', '天'), ('WEEK', '周'), ('MONTH', '月'), ('QUARTER', '季度'), ('YEAR', '年')], max_length=16, verbose_name='周期单位')),
                ('cycle_value', models.PositiveIntegerField(default=1, verbose_name='周期数值')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('next_due_at', models.DateTimeField(db_index=True, verbose_name='下次到期')),
                ('lead_days', models.PositiveIntegerField(default=3, verbose_name='提前生成天数')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '紧急')], default='MEDIUM', max_length=16, verbose_name='工单优先级')),
                ('status', models.CharField(choices=[('ACTIVE', '运行中'), ('PAUSED', '已暂停'), ('ARCHIVED', '已归档')], db_index=True, default='ACTIVE', max_length=16, verbose_name='状态')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='最近生成时间')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.equipmentcomponent', verbose_name='部件')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='默认负责人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.equipment', verbose_name='设备')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='facilities.warehouse', verbose_name='仓库')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='maintenance.maintenancetemplate', verbose_name='维保模板')),
            ],
            options={
                'verbose_name': '维保计划',
                'verbose_name_plural': '维保计划',
                'ordering': ['next_due_at', 'warehouse__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTemplateTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(verbose_name='顺序')),
                ('title', models.CharField(max_length=160, verbose_name='任务标题')),
                ('instructions', models.TextField(blank=True, verbose_name='操作说明')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, verbose_name='预计分钟')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='必须上传照片')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.maintenancetemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '模板任务',
                'verbose_name_plural': '模板任务',
                'ordering': ['template', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancetemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uniq_maintenance_template_version'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['status', 'next_due_at'], name='maintenance_status_32945f_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_value__gt', 0)), name='maintenance_cycle_value_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('lead_days__gte', 0)), name='maintenance_lead_days_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='maintenancetemplatetask',
            constraint=models.UniqueConstraint(fields=('template', 'sequence'), name='uniq_template_task_sequence'),
        ),
    ]
