# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.assetcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '设备分类',
                'verbose_name_plural': '设备分类',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=64, verbose_name='设备编码')),
                ('name', models.CharField(max_length=120, verbose_name='设备名称')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='序列号')),
                ('commissioned_on', models.DateField(blank=True, null=True, verbose_name='投产日期')),
                ('location_detail', models.CharField(blank=True, max_length=255, verbose_name='位置')),
                ('criticality', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '关键')], db_index=True, default='MEDIUM', max_length=16, verbose_name='关键度')),
                ('status', models.CharField(choices=[('ACTIVE', '运行中'), ('INACTIVE', '停用'), ('RETIRED', '已退役')], db_index=True, default='ACTIVE', max_length=16, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展属性')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='assets.assetcategory', verbose_name='设备分类')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='facilities.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '自动化设备',
                'verbose_name_plural': '自动化设备',
                'ordering': ['warehouse__code', 'asset_code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='部件编码')),
                ('name', models.CharField(max_length=120, verbose_name='部件名称')),
                ('component_type', models.CharField(blank=True, max_length=80, verbose_name='部件类型')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='序列号')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用')], default='ACTIVE', max_length=16, verbose_name='状态')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.equipment', verbose_name='设备')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.equipmentcomponent', verbose_name='上级部件')),
            ],
            options={
                'verbose_name': '设备部件',
                'verbose_name_plural': '设备部件',
                'ordering': ['equipment', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['warehouse', 'status', 'criticality'], name='assets_equi_warehou_ee1165_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('warehouse', 'asset_code'), name='uniq_asset_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='equipmentcomponent',
            constraint=models.UniqueConstraint(fields=('equipment', 'code'), name='uniq_component_code_per_equipment'),
        ),
    ]
