# Generated by Django 5.2.17 on 2026-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '投产'), ('INACTIVE', '停用'), ('TRIAL', '试运行'), ('COMMISSIONING', '调试'), ('RETIRED', '废弃')], db_index=True, default='ACTIVE', max_length=16, verbose_name='状态'),
        ),
    ]
