# Generated by Django 5.2.17 on 2026-08-18 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('WORK_ORDER_CREATED', '新工单'), ('WORK_ORDER_DUE', '工单到期提醒'), ('WORK_ORDER_OVERDUE', '工单逾期'), ('SYSTEM', '系统消息')], max_length=32, verbose_name='通知类型')),
                ('title', models.CharField(max_length=180, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('entity_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='对象 ID')),
                ('dedup_key', models.CharField(blank=True, max_length=160, null=True, unique=True, verbose_name='幂等键')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__950da6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('IN_APP', '站内'), ('EMAIL', '邮件')], default='IN_APP', max_length=16, verbose_name='渠道')),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('SENT', '已发送'), ('FAILED', '失败')], db_index=True, default='SENT', max_length=16, verbose_name='发送状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('error_message', models.TextField(blank=True, verbose_name='失败原因')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知接收记录',
                'verbose_name_plural': '通知接收记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_bd6a1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'user', 'channel'), name='uniq_notification_user_channel')],
            },
        ),
    ]
